package com.shopstyle.msbffshop.clients.enums;

public enum Status {

	PROCESSING_PAYMENT,
	PAYMENT_NOT_FOUND,
	PAYMENT_INACTIVE,
	PAYMENT_NOT_INSTALLMENT,
	PAYMENT_AMOUNT_NOT_AVAILABLE,
	PAYMENT_SUCCESSFUL
}
